# Generated by Django 6.0.4 on 2026-04-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес электронной почты",
                        max_length=150,
                        unique=True,
                        verbose_name="e-mail",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите Ф.И.О.",
                        max_length=150,
                        verbose_name="Ф.И.О.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Тема письма")),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Тело письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["title"],
            },
        ),
    ]
